# Generated by Django 3.2.18 on 2023-03-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
